/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://n54uemkf2jcing5px6g2tu5zgm.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ohbhy2elqzcthbqgmctzq5mzem",
    "aws_cognito_identity_pool_id": "eu-west-2:c0eddfc6-17d7-47e1-a5cf-448ecd1f59e7",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_PfAJ56K18",
    "aws_user_pools_web_client_id": "or74ng3bmtpjr4fe5hilt8qm6",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "media180607-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2"
};


export default awsmobile;
